spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shop"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        messaging: DEBUG
